server:
    port: 9000
spring:
  application:
    name: config
  cloud:
   config:
    server:
      git:
        uri: https://github.com/xinaml/luck
        username: xinaml
        password: passwd
