#服务名
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: order
        uri: http://localhost:8082/test
        predicates:
        - Path=/order/**
        filters:
        - StripPrefix=1
      - id: storage
        uri: http://localhost:8081/test
        predicates:
        - Path=/storage/**
        filters:
        - StripPrefix=1

#端口
server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

